### ISSUE TITLE
Improved Track power and effect?

### ISSUE THREAD

**Issue by patrik3k** [sfalkman/ngenic-hass-platform#4]
Hi, 
I'm using you component with an Ngenic Tune plus a Track. Its great, huge thanks for creating it.
I have fixed a small number of things regarding the Track handling. Is this still maintained and if so what is the best way to contribute?

Sorry if this is out of place but Im pretty much a noob when it comes to github and python as I left my programming days behind me a long time ago.
All the best, 
Patrik

**Comment by sfalkman** [comment]
Hey,
Sounds great! Contributions are always welcome, especially for the Track since I don't have my own to test with :)

To contribute, you should fork the project and create a pull request of your fixes. I will review and merge them to the master branch.

This looks like a good tutorial you can follow: https://github.com/firstcontributions/first-contributions

If you need any help just ask, your contributions are appreciated!

**Comment by sfalkman** [comment]
https://github.com/sfalkman/ngenic-hass-platform/pull/5 and https://github.com/sfalkman/ngenic-hass-platform/pull/6 merged, closing this issue.
